# Generated by Django 5.0.4 on 2024-06-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_is_publish_material_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='is_publish',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='material',
            name='view_count',
        ),
        migrations.AddField(
            model_name='material',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
    ]
